### ISSUE TITLE
se borra los espacios iniciales en las líneas de código

### ISSUE THREAD

**Issue by yojuancarlos** [Hponky/hexo#2]
### Check List

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting).
- [ ] I have already searched existing issues and they are not help to me.
- [ ] I examined error or warning messages and it's difficult to solve.
- [ ] I am using the [latest](https://github.com/hexojs/hexo/releases) version of Hexo. (run `hexo version` to check)
- [ ] My Node.js is matched [the required version](https://hexo.io/docs/#Required-Node-js-version).

### Expected behavior

Se espera que cada línea de texto salga con sus espacios iniciales

### Actual behavior

Se elimina los espacios iniciales en cada párrafo
![image](https://github.com/Hardev1/hexo/assets/56267375/a76bf79d-1a70-48c3-91c1-d0bd5431178f)
Pero si el primer párrafo no tiene líneas iniciales el error se soluciona
![image](https://github.com/Hardev1/hexo/assets/56267375/a5b4f68f-e67b-421d-a189-c483fa538f48)

### How to reproduce?

Dentro de la carpeta _posts en el archivo test.md escribiendo el siguiente código
![image](https://github.com/Hardev1/hexo/assets/56267375/f2a99d38-6f5f-4d0c-9c88-7f3df8096067)

### Is the problem still there under `Safe mode`?

si

### Your Node.js & npm version

```text
Node version
v18.12.1
NPM version
8.19.2
```

### Your Hexo and Plugin version

```text
hexo-site@0.0.0 D:\sofware 3\proyecto 1\hexo\blog
├── hexo-generator-archive@2.0.0
├── hexo-generator-category@2.0.0
├── hexo-generator-index@3.0.0
├── hexo-generator-tag@2.0.0
├── hexo-renderer-ejs@2.0.0
├── hexo-renderer-marked@6.2.0
├── hexo-renderer-stylus@3.0.1
├── hexo-server@3.0.0
├── hexo-theme-landscape@1.0.0
└── hexo@7.1.1
```

### Your `package.json`

```json
{
  "name": "hexo",
  "version": "7.1.1",
  "description": "A fast, simple & powerful blog framework, powered by Node.js.",
  "main": "dist/hexo",
  "bin": {
    "hexo": "./bin/hexo"
  },
  "scripts": {
    "prepublishOnly": "npm install && npm run clean && npm run build",
    "build": "tsc -b",
    "clean": "tsc -b --clean",
    "eslint": "eslint lib test",
    "pretest": "npm run clean && npm run build",
    "test": "mocha test/scripts/**/*.ts --require ts-node/register",
    "test-cov": "c8 --reporter=lcovonly npm test -- --no-parallel",
    "prepare": "husky install"
  },
  "files": [
    "dist/",
    "bin/"
  ],
  "types": "./dist/hexo/index.d.ts",
  "repository": "hexojs/hexo",
  "homepage": "https://hexo.io/",
  "funding": {
    "type": "opencollective",
    "url": "https://opencollective.com/hexo"
  },
  "keywords": [
    "website",
    "blog",
    "cms",
    "framework",
    "hexo"
  ],
  "author": "Tommy Chen <tommy351@gmail.com> (https://zespia.tw)",
  "maintainers": [
    "Abner Chou <hi@abnerchou.me> (https://abnerchou.me)"
  ],
  "license": "MIT",
  "dependencies": {
    "abbrev": "^2.0.0",
    "archy": "^1.0.0",
    "bluebird": "^3.7.2",
    "hexo-cli": "^4.3.0",
    "hexo-front-matter": "^4.2.1",
    "hexo-fs": "^4.1.1",
    "hexo-i18n": "^2.0.0",
    "hexo-log": "^4.0.1",
    "hexo-util": "^3.0.1",
    "js-yaml": "^4.1.0",
    "js-yaml-js-types": "^1.0.0",
    "micromatch": "^4.0.4",
    "moize": "^6.1.6",
    "moment": "^2.29.1",
    "moment-timezone": "^0.5.34",
    "nunjucks": "^3.2.3",
    "picocolors": "^1.0.0",
    "pretty-hrtime": "^1.0.3",
    "resolve": "^1.22.0",
    "strip-ansi": "^6.0.0",
    "text-table": "^0.2.0",
    "tildify": "^2.0.0",
    "titlecase": "^1.1.3",
    "warehouse": "^5.0.1"
  },
  "devDependencies": {
    "0x": "^5.1.2",
    "@types/abbrev": "^1.1.3",
    "@types/bluebird": "^3.5.37",
    "@types/chai": "^4.3.11",
    "@types/js-yaml": "^4.0.9",
    "@types/mocha": "^10.0.6",
    "@types/node": "^18.11.8 <18.19.9",
    "@types/nunjucks": "^3.2.2",
    "@types/sinon": "^17.0.3",
    "@types/text-table": "^0.2.4",
    "c8": "^9.0.0",
    "chai": "^4.3.6",
    "cheerio": "0.22.0",
    "decache": "^4.6.1",
    "eslint": "^8.48.0",
    "eslint-config-hexo": "^5.0.0",
    "hexo-renderer-marked": "^6.0.0",
    "husky": "^8.0.1",
    "lint-staged": "^15.2.0",
    "mocha": "^10.0.0",
    "sinon": "^17.0.1",
    "ts-node": "^10.9.1",
    "typescript": "^5.3.2"
  },
  "engines": {
    "node": ">=14"
  }
}
```

### Your site's `_config.yml` (Optional)

```yaml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle: ''
description: ''
keywords:
author: John Doe
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: landscape

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''
```
